services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile

    container_name: ecommerce-backend

    ports:
      - "5000:5000"

    env_file:
      - .env

    restart: unless-stopped
    networks:
      - ecommerce-network
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile

    container_name: ecommerce-frontend

    ports:
      - "3000:3000"

  

    depends_on:
      - backend

    restart: unless-stopped

    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

